logging:
  level:
    org.springframework.security: INFO
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

security:
  oauth2:
    resource:
      userInfoUri: http://auth-service:5000/uaa/users/current
