spring:
  data:
    mongodb:
      uri: ${CLIENT_SERIVCE_DB_URI}

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9000/auth/users/current

server:
  servlet:
    context-path: /clients
  port: 7000